SELECT PUB.NAME PUBLISHER,
	PL.NAME PLACE,
	date_part('year',MIN(MAN.EARLIEST))::int EARLIEST,
	date_part('year',MAX(MAN.LATEST))::int LATEST
FROM PUBLISHERS PUB,
	PLACES PL,
	MANIFESTATIONS MAN,
	MANIFESTATIONS_PUBLISHERS MP
WHERE PUB.ID = MP.PUBLISHER_ID
	AND MAN.ID = MP.MANIFESTATION_ID
	AND PL.ID = MP.PLACE_ID
GROUP BY PUBLISHER,
	PLACE
ORDER BY PUBLISHER,
	EARLIEST,
	LATEST
