SELECT PUB.NAME PUBLISHER,
	PL.NAME PLACE,
	date_part('year',EARLIEST)::int EARLIEST,
	date_part('year',LATEST)::int LATEST
FROM MANIFESTATIONS MAN,
	MANIFESTATIONS_PUBLISHERS MP,
	PLACES PL,
	PUBLISHERS PUB
WHERE MAN.ID = MP.MANIFESTATION_ID
	AND PL.ID = MP.PLACE_ID
	AND PUB.ID = MP.PUBLISHER_ID
GROUP BY PUBLISHER,
	PLACE,
	EARLIEST,
	LATEST
ORDER BY PUBLISHER,
	EARLIEST,
	LATEST
